### ISSUE TITLE
Mobile Menu issue when using anchor links in Nav

### ISSUE THREAD

**Issue by danp-dev** [onwidget/astrowind#165]
I build out some sections on the homepage of the template, I added anchor links to the navbar so a site user can jump between sections of the page. 

When using the site on mobile, I noticed that the links work (they take you to the correct section of the page as I can see the url change) But the mobile menu does not disappear.

The BasicScripts.Astro file has an attach event and an onpageshow event that look to be handling the display property for the mobile menu. 

attachEvent('[data-aw-toggle-menu]', 'click', function (_, elem) {
      elem.classList.toggle('expanded');
      document.body.classList.toggle('overflow-hidden');
      document.getElementById('header')?.classList.toggle('h-screen');
      document.querySelector('#header nav')?.classList.toggle('hidden');
    });
    
    window.onpageshow = function () {
    document.documentElement.classList.add('motion-safe:scroll-smooth');
    const elem = document.querySelector('[data-aw-toggle-menu]');
    if (elem) {
      elem.classList.remove('expanded');
    }
    document.body.classList.remove('overflow-hidden');
    document.getElementById('header')?.classList.remove('h-screen');
    document.querySelector('#header nav')?.classList.add('hidden');
  };

**Comment by prototypa** [comment]
Hi @danp-dev 

For now we add a small fix in `BasicScripts.astro` to solve this problem. Please check that everything is as you expect and let us know. Thank you.

Commit: https://github.com/onwidget/astrowind/commit/8ff3675cfaf946daec006769fce9bbeac25d395e
