### ISSUE TITLE
[Cleanup] Fix <LatestPosts /> Props and usage

### ISSUE THREAD

**Issue by IlyaKukarkin** [onwidget/astrowind#189]
Small fixes for the `<LatestPosts />` component:

1. Fix for the `Props`
    2. Remove `postIds` prop
    3. Add `count` prop
4. Remove `postIds` from `index.astro` file

**Comment by prototypa** [comment]
Hi @IlyaKukarkin 

We approve your PR that fixes this. Thank you so much.
