### ISSUE TITLE
astro-compress removal

### ISSUE THREAD

**Issue by GrantBirki** [onwidget/astrowind#211]
# astro-compress removal

I can see from the commit history in this project that `astro-compress` has been removed as its currently busted. I have a "fork" (my own version) of this project, and a maintainer for Astro was very kind and opened a pull request today to fix my project. I figured I would link it here as it may be beneficial to review

https://github.com/GrantBirki/astrowind/pull/217

**Comment by TheOtterlord** [comment]
Just checked, looks like they removed it in ff38a2cdac5f05b6ba7b69b625aab09879e69c85 and 632c2a84a74e91db60f3b2ad953941b816b3e559!

**Comment by prototypa** [comment]
Thanks @GrantBirki and @TheOtterlord
