### ISSUE TITLE
The avatar of the testimonials is displayed incorrectly

### ISSUE THREAD

**Issue by chrislaai** [onwidget/astrowind#242]
![101452@2x](https://github.com/onwidget/astrowind/assets/134155599/3d7e72e7-be1b-4f1e-892b-76a4bc3a1f13)

**Comment by prototypa** [comment]
Hi @chrislaai, thank you for this. 

They have been resolved here in these two commits:

- https://github.com/onwidget/astrowind/commit/f03c8d7f8f8e5a80cd56e35e09cf392ef2a53cf5
- https://github.com/prototypa/astrowind/commit/57cbb7d01548243d6b097488b1f59bb9e155a364
