### ISSUE TITLE
YouTube Embed Not Working in v3.0

### ISSUE THREAD

**Issue by jawills** [onwidget/astrowind#253]
When using the plugin 'astro-embed' in md or mdx files in a blog post, the CSS / javascript is not being pulled correctly from the plugin. It's unclear if there are other issues downstream issues but it seems to be related to how the posts are rendered through the template

Source code: https://github.com/jawills/youtube-embed-debug
Live Site: https://youtube-embed-debug.vercel.app/astrowind-template-in-depth
https://github.com/delucis/astro-embed/issues/57

**Comment by prototypa** [comment]
Hi @jawills 

I was trying a new project with Astro 3 and `astro-embed` and it gave me an error in the console with this configuration:

```js
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import preact from '@astrojs/preact';
import embeds from 'astro-embed/integration';

// https://astro.build/config
export default defineConfig({
   integrations: [
      preact(),
      mdx(),
      embeds(),
   ],
});
```

Error:

```
Auto imports in .mdx files won’t work!
Move the MDX integration after auto-import
```

When I put embeds() before mdx() it worked.

Example:

```js
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import preact from '@astrojs/preact';
import embeds from 'astro-embed/integration';

// https://astro.build/config
export default defineConfig({
   integrations: [
      preact(),
      embeds(),
      mdx()
   ],
});
```
