### ISSUE TITLE
Internal server error generating blog page

### ISSUE THREAD

**Issue by kymillev** [onwidget/astrowind#269]
Just started with a fresh project, locally. When I try to load the blog page at /blog I get the following error:

`06:46:02 PM [vite] Internal server error: Failed to resolve entry for package "D:\blog". The package may have incorrect main/module/exports specified in its package.json.`

When I rename the blog pathname in the config.yaml file to "test" and restart, the page works as intended at /test. I'm sure this error is happening because I have a local folder named "blog" (the project code is in D:\website, the other folder is D:\blog). When I rename the local blog folder to something else, everything works as intended.

**Comment by prototypa** [comment]
Hello @kymillev 

Thanks for reporting it. This problem that you explain seems to be something very specific for the _Windows_ operating system and only if the `blog` folder exists in root.

Right now I don't have the resources to reproduce the error. I'll do it soon and I'll let you know if I find a solution.

If anyone else who reads this Issue and uses Windows can know how to solve it, please.
Thank you.
