### ISSUE TITLE
The header shadow should only be triggered for sticky headers

### ISSUE THREAD

**Issue by atomobianco** [onwidget/astrowind#279]
Hello and thank you for this useful theme!
I found a small issue with styling when using `Header` when the property `isSticky` is false, that is when the header should scroll with the rest of the page.
The method `appyHeaderStylesOnScroll` is called no matter what the header stickiness is, and this methods adds/removes the `scroll` class to the element. This propagates to the CSS adding a shadow to it. 

![Screenshot from 2023-09-25 16-08-17](https://github.com/onwidget/astrowind/assets/7416867/f0daf252-b758-4826-8b3c-ab481962fb66)

**Comment by prototypa** [comment]
Hello everyone, we know about the long delay. We were working on a complex project, we are back. In the discussion area we will present the new fixed and defined update schedule. Thanks for the patience.

**Comment by prototypa** [comment]
Hi @atomobianco 

Thanks for this, now it was fixed: https://github.com/onwidget/astrowind/commit/ee5bb1747a6f19f9ca50ba98eb20d9ee3b2ce5a1
