### ISSUE TITLE
Table messes up navbar on mobile

### ISSUE THREAD

**Issue by piotrpdev** [onwidget/astrowind#295]
## Chrome Version 119.0.6045.124 (Official Build) (64-bit) Windows 11

https://github.com/onwidget/astrowind/assets/99439005/0585954f-9342-4786-8974-ef4879f0e86b

---

## Chrome Version 119.0.6045.124 (Official Build) (64-bit) Android 13, Samsung Galaxy A51 (SM-A515F)

https://github.com/onwidget/astrowind/assets/99439005/ef9e0e49-2a6d-4c68-a017-3f385be268ad

**Comment by prototypa** [comment]
Hello everyone, we know about the long delay. We were working on a complex project, we are back. In the discussion area we will present the new fixed and defined update schedule. Thanks for the patience.

**Comment by prototypa** [comment]
Hi @piotrpdev 

Thanks for finding this bug. We have solved this by wrapping all the markdown tables in a scrollable div tag using a rehype plugin: https://github.com/onwidget/astrowind/commit/0dc98a56f2fb24148779e7844b2ab9e7eabd2150

Anything else you find, let us know, thank you very much.
