### ISSUE TITLE
button on contact form not working

### ISSUE THREAD

**Issue by SveDar** [onwidget/astrowind#299]
Hello!
tring to integrate netlify form for submishons i notice that the button in Form.astro its not responding. I used old versino befor adding '~/components/ui/Button.astro' component and it worked on clik now its not. 
![image](https://github.com/onwidget/astrowind/assets/37973903/bb993abb-9e60-449e-82af-998f113200f7)

**Comment by prototypa** [comment]
Hi @SveDar 

Thanks for the feedback, you are correct. When we updated from `<button>` to `<Button>` we didn't take this into account.

It is already resolved in: https://github.com/onwidget/astrowind/commit/9818cd08b86c85f95a0789a79c1631135be80a7d
