### ISSUE TITLE
How to update the icon library

### ISSUE THREAD

**Issue by lidaof** [onwidget/astrowind#300]
Hello,

I am trying to use the new X icon, but it says `Error: Not Found: "brand-x" in pack "tabler"`
I tried updating `npm install -D @iconify-json/tabler` and `npm install -D astro-icon` which doesn't work
I am using version 0.9.8, current site has been modified many files...not quite easy to switch to the latest version...

Thank you!

**Comment by danielkoch** [comment]
Without logs or errors it's hard to understand why the update is not working. In general the icon is available in the latest release: https://icon-sets.iconify.design/?query=brand-x

`@iconify-json/tabler` is currently in version `1.1.100` (https://www.npmjs.com/package/@iconify-json/tabler). Looks your copy of the theme is outdated.
If I remember it correctly I had some issues on updating on `v1` of `@iconify-json/tabler`. I think I solved it by using the future/next version of `astro-icon` (`npm i -D astro-icon@next`).

**Comment by lidaof** [comment]
Thank you for the comment! @danielkoch
