### ISSUE TITLE
Update for Astro 4.0

### ISSUE THREAD

**Issue by Immortalin** [onwidget/astrowind#307]
https://astro.build/blog/astro-4/

**Comment by prototypa** [comment]
Hi @Immortalin and @abdelkareemkobo 

Thanks for the feedback. I have already updated the template to [Astro 4.0](https://astro.build/blog/astro-4/): https://github.com/onwidget/astrowind/commit/0be813aba250b132381dfd7b64fa1b569c7b4719

The errors were mostly related to the fact that the latest versions of [@astrolib/seo](https://www.npmjs.com/package/@astrolib/seo) and [@astrolib/analytics](https://www.npmjs.com/package/@astrolib/analytics) dependencies did not support this new version of Astro. These dependencies have already been updated.

If you update these dependencies to the following versions everything will work correctly:
- @astrolib/seo: 1.0.0-beta.5
- @astrolib/analytics: 0.5.0

Any problem let me know.

**Comment by canomogollon** [comment]
How to update the template on an existing site the command "npm update" updates the dependencies but not the template and the command "npx @astrojs/upgrade " updates the framework, any idea ?  --- Thanks
