### ISSUE TITLE
Zoom Level/Font Size is different for Edge Chromium compared to Chrome and Firefox 

### ISSUE THREAD

**Issue by koolkunz** [onwidget/astrowind#312]
For some reason the website shows up differently on Edge browser. Screenshots attached:

1) Firefox
![Screenshot (227)](https://github.com/onwidget/astrowind/assets/6692008/51575468-708e-4177-9740-c04b7ab37bf4)

2) Google Chrome
![Screenshot (228)](https://github.com/onwidget/astrowind/assets/6692008/6b75daa1-9a0c-47e1-b2f9-c5c73a06acbe)

3) Microsoft Edge (Chromium)
![Screenshot (229)](https://github.com/onwidget/astrowind/assets/6692008/4a6ae945-74df-4ec2-adc8-13b6ba9b0b57)

**Comment by thkruz** [comment]
Zoom settings are not synced between browsers and it appears that all font, padding, and margins are being impacted.  Can you confirm that all three browsers are all set to 100% zoom (ctrl+0 on windows). If you check the settings in the top right hand corner there are zoom settings in each browser. If you zoomed out while using Edge on another page it would explain everything.

If that didn't fix it, can you post your screen resolution? I am trying to recreate it and can't. The other question, to rule stuff out, is can you just verify that another page like Google.com looks the same on all three browsers?

**Comment by koolkunz** [comment]
@thkruz I can confirm that all browsers are set to 100% zoom. My screen resolution is 1920x1080 and all other websites like google.com look the same on all browsers.

**Comment by thkruz** [comment]
I set my resolution to 1920x1080 and in Brave, Chrome, and Edge I see exactly what you see in Edge. I am using the alignment of the "s" in websites with the RSS icon and how much of the astronaut is visible.

Edge adds padding to the outside of the website which is modifying the innerWidth property of the window and making it different (not by much) than the others.

To get any of my browsers to look like your Firefox or Chrome screenshots I need to make the innerWidth between 1535 and 1555px. I can do that by resizing the window or by changing the zoom - doesn't matter how, that is the trigger. Less than 1535px changes the sizing and less than 1280px hides some of the text. No matter how much bigger I make the screen, there is no way to get the "s" lined up with the RSS feed with any other width setting.

Can you open Dev Tools and type window.innerWidth in the console to figure out the pixel width of each of your browsers?

**Comment by koolkunz** [comment]
@thkruz Here are the window.innerWidth values for me with all browsers set to 100% zoom and maximized window size:
1. Firefox : 1536
2. Chrome : 1536
3. Edge: 1528

**Comment by thkruz** [comment]
Mystery solved then. The layout changes based on the size of the window and Edge adds padding around the windows making it slightly smaller than the other browsers. 

It is just a bad coincidence that your pixel density lines up that the little bit of difference means Edge is a large layout and everything else is an xl layout.

**Comment by thkruz** [comment]
@koolkunz if that was all it was then you should close the issue. Glad it wasn't an actual bug.
