### ISSUE TITLE
sharp error

### ISSUE THREAD

**Issue by Dacong-wu** [onwidget/astrowind#313]
[vite]: Rollup failed to resolve import "sharp" from "E:/qtum-work/github-code/astrowind/node_modules/astro/dist/assets/services/sharp.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to

**Comment by Dacong-wu** [comment]
please use pnpm，it can install sharp

**Comment by soranauts** [comment]
> [vite]: Rollup failed to resolve import "sharp" from "E:/qtum-work/github-code/astrowind/node_modules/astro/dist/assets/services/sharp.js". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to

I'm having the same issue. The deployment from GitHub fails. What's the best way to fix this? Thanks.

**Comment by soranauts** [comment]
Seems to be an issue on Vercel when deploying. What's the best solution for this?

**Comment by Dacong-wu** [comment]
when I deployed it, he still had problems 
just like  #314

**Comment by soranauts** [comment]
> when I deployed it, he still had problems just like #314

I removed `astro-compress` from dependencies and config file. Works great, barely notice a difference.

**Comment by Dacong-wu** [comment]
can use Squoosh
[astro-doc](https://docs.astro.build/zh-cn/guides/images/#%E9%BB%98%E8%AE%A4%E5%9B%BE%E5%83%8F%E6%9C%8D%E5%8A%A1)

**Comment by prototypa** [comment]
Hi @Dacong-wu and @soranauts 

Thank you for this. I've been checking and it seems that it is an existing problem with the latest version of Sharp. These two tickets from the respective Sharp and Vercel repositories are reviewing the issue. In addition, there are many forums talking about Sharp failures on other platforms.

https://github.com/lovell/sharp/issues/3870
https://github.com/vercel/nft/issues/371

For now we have temporarily removed astro-compress and also migrated from Sharp to Squoosh. As soon as we have a clear solution for Sharp we will revert the changes.

If you have any more problems, please let me know.
Thanks
