### ISSUE TITLE
output: 'static' to output: 'server'

### ISSUE THREAD

**Issue by daherlive** [onwidget/astrowind#349]
Team, I'm facing some difficulties on  server render on Vercel with Astrowind theme. Following the instructions, I`ve changed 
`output: 'static'` to `output: 'server',` and added  `import vercelServerless from `'@astrojs/vercel/serverless';` and also   added `adapter: vercelServerless(),` . 

But in production ( with Vercel) I got a 404 error.

**Comment by prototypa** [comment]
Hi @daherlive 

It is not an issue, the template only supports `output: static` and `output: hybrid`.

In the **Astrowind 2** version we will try to resolve that limitation.

Thanks
