### ISSUE TITLE
npm run build fails due to getImage() return type GetImageResult

### ISSUE THREAD

**Issue by ryanlauterbach** [onwidget/astrowind#364]
`$ npm run build

> astrowind@1.0.0-beta.17 build
> astro check && astro build

Re-optimizing dependencies because lockfile has changed
13:17:31 [vite] Re-optimizing dependencies because vite config has changed
13:17:31 Types generated 177ms
13:17:31 [check] Getting diagnostics for Astro files in /home/ryan/Work/astro/astrowind...
src/utils/images.ts:84:64 - error ts(2339): Property 'height' does not exist on type 'GetImageResult'.

84             height: typeof _image.height === 'number' ? _image.height : undefined,
                                                                  ~~~~~~
src/utils/images.ts:84:35 - error ts(2339): Property 'height' does not exist on type 'GetImageResult'.

84             height: typeof _image.height === 'number' ? _image.height : undefined,
                                     ~~~~~~
src/utils/images.ts:83:62 - error ts(2339): Property 'width' does not exist on type 'GetImageResult'.

83             width: typeof _image.width === 'number' ? _image.width : undefined,
                                                                ~~~~~
src/utils/images.ts:83:34 - error ts(2339): Property 'width' does not exist on type 'GetImageResult'.

83             width: typeof _image.width === 'number' ? _image.width : undefined,
                                    ~~~~~

Result (95 files):
- 4 errors
- 0 warnings
- 0 hints`

**Comment by prototypa** [comment]
Hi @ryanlauterbach 

Was this issue resolved with @dudil PR https://github.com/dudil/astrowind/commit/74e2435570e5d92f5c1e378b280f926a252ee7e7?

**Comment by djfdat** [comment]
I had a different fix for this locally, but not familiar enough to know what's the correct fix. But what I did was change:
_image.width
to
_image.attributes.width

I don't know why I did this, but it fixed the issue. I also did it for _image.height, but not for _image.src, since it wasn't part of the error.

**Comment by ryanlauterbach** [comment]
I did the same fix as @djfdat locally. The build error is gone, however if the image width is now access by 

`_image.attributes.width`

then the fix

`'width' in _image`

will just return undefined I think. Also the navigation links don't work locally or on the vercel demo site for me. I'm using firefox and chrome on linux.

**Comment by dudil** [comment]
@ryanlauterbach had you tried the fix provided in the PR?
That was working fine for me but haven't checked on firefox - only chrome / edge / safari.

@djfdat  - was that fixing the error or just removing the error message?
