### ISSUE TITLE
Handling forms

### ISSUE THREAD

**Issue by dominikwozniak** [onwidget/astrowind#370]
Hey, I tried to make a contact and newsletter forms . On my development environment, everything works after changing the output to "server". However, when deployed to Vercel, I can't handle the forms. 
I saw an issue explaining that only "hybrid" or "static" output is possible.  https://github.com/onwidget/astrowind/issues/349

For form handling I wanted to use the example from Astro docs: https://docs.astro.build/en/recipes/build-forms/

Can you advise how I can handle these forms?

**Comment by prototypa** [comment]
Hi @dominikwozniak 

**AstroWind** for now only works with export `static` or `hybrid`, not yet `server`. If you want to make a contact form you will have to use an external service.

https://github.com/onwidget/astrowind/discussions/239
