### ISSUE TITLE
CallToAction incorrectly extends HTMLAttributes

### ISSUE THREAD

**Issue by dawaltconley** [onwidget/astrowind#396]
HTMLAttributes takes a string as its generic, currently it's being passed an undefined type `a`.

```ts
export interface CallToAction extends HTMLAttributes<a> {
  // ...
}
```

However, Astro throws type errors if pass a type like this to a component with spread syntax, because of the `slot` property. So the correct typing would be:

```ts
export interface CallToAction extends Omit<HTMLAttributes<'a'>, 'slot'> {
  // ...
}
```

**Comment by prototypa** [comment]
Hi @dawaltconley 

With your PR and with some adjustments that I made based on the comment you put in the PR about missing types, **AstroWind** now passes the `astro check` validation

- https://github.com/onwidget/astrowind/pull/399
- https://github.com/onwidget/astrowind/commit/a2187f09915e4c04c22257c6127b05fe596f7a9e

Thanks, I'm going to close the Issue.
