### ISSUE TITLE
Fetch content from backend - HTML is coming with <p>and breaks the design.

### ISSUE THREAD

**Issue by Yoobe** [onwidget/astrowind#406]
Hi,

I am implementing this template with Directus backend where I use HTML editor for some fields (content, subtitle, etc.)
The HTML text contains the "p" tag for each paragraph and this impacts the UI.

For example, in the Hero component, the subtitle or content fields with "p" will display a different font compared to default design.

How can I fix this in the template? I imagine I should modify the CSS to avoid to modify the font (type, size) in the <p> within some classes?

I tried to use a MD editor in Directus and the marked.parse() in Astro.
This has the same effect on the text. A "p" tag is added by marked, I think.

**Comment by Yoobe** [comment]
I tried to use a MD editor in Directus and the marked.parse() in Astro.
This has the same effect on the text. A <p> is added by marked, I think.

**Comment by Yoobe** [comment]
I fixed this by change the content of the components.

**Comment by prototypa** [comment]
Hi @Yoobe 

We believe this is not an issue with the template but with the configuration you are following when connecting to a CMS.  If your CMS does not return unnecessary `<p>` tags everything will work correctly.  Perhaps something that we do let work on is a detailed guide for what to do when situations like that occur.  We will take that into account, thank you.  Let's close this issue.
