### ISSUE TITLE
Prettier inconsistencies

### ISSUE THREAD

**Issue by ShoGinn** [onwidget/astrowind#430]
When running Prettier on a base setup, many files are corrected under the current settings.

**Comment by prototypa** [comment]
Hi @ShoGinn 

Thanks for this, it was resolved with:
https://github.com/onwidget/astrowind/commit/a606b34a194d90057bb55503aea33d1419d9e1d4

The next task is to automate this and other tasks.

**Comment by ShoGinn** [comment]
I think using pre-commit hooks with a tool such as Husky https://typicode.github.io/husky/

Just an idea!
