### ISSUE TITLE
@astrolib/seo -- HTML5 Validation Errors

### ISSUE THREAD

**Issue by ShoGinn** [onwidget/astrowind#435]
I opened an issue on https://github.com/onwidget/astrolib/issues/15#issue-2271586403

The issue is that meta tags and link tags in SEO are generated using the void style, which is against HTML standards.

More details are in the dependencies, but it plays a factor for astrowind.

<details><summary>Details</summary>
<p>

Example from `404.html`
```sh
  1:1926  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:1970  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2036  error  Expected omitted end tag <link> instead of self-closing element <link/>  void-style
  1:2083  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2182  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2253  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2297  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2403  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2444  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
  1:2507  error  Expected omitted end tag <meta> instead of self-closing element <meta/>  void-style
```

</p>
</details>

**Comment by prototypa** [comment]
Hi @ShoGinn 

Thank you for this. Very valid. I was quickly reviewing the PR in `astrolib` and it looks very interesting. As soon as possible I do a deep review and approve the PR.

**Comment by ShoGinn** [comment]
@prototypa Thanks for indulging my contributions!

**Comment by prototypa** [comment]
Hi @ShoGinn 

Fixed with https://github.com/onwidget/astrowind/commit/fd56aed180678efc03f397834e419a3fd5e5b99d

Thanks
