### ISSUE TITLE
Issues with peer dependencies found: Compress

### ISSUE THREAD

**Issue by PabloC** [onwidget/astrowind#438]
Unmet dependency spotted. 

<img width="705" alt="image" src="https://github.com/onwidget/astrowind/assets/764/654d1c7e-9b43-407d-b267-9bc840045a91">

**Comment by JuliusBairaktaris** [comment]
See: https://github.com/PlayForm/Compress/issues/334

**Comment by prototypa** [comment]
Fixed https://github.com/PlayForm/Compress/issues/334#issuecomment-2103071875
