### ISSUE TITLE
Safari only: Related Posts multi-line header links behave unhandy

### ISSUE THREAD

**Issue by OlgaBubermanOB** [onwidget/astrowind#441]
In Safari: multi-line links behave unhandy when line height is more than normal: between the lines cursor turns back to pointer, link is unclickable (only between the lines) and not highlighted. Chrome and Firefox not affected.

https://github.com/onwidget/astrowind/assets/83764067/81ba59fa-3a75-465b-979b-8ad5ead2485e

**Comment by prototypa** [comment]
Fixed with your PR https://github.com/onwidget/astrowind/pull/442 
Thanks
