### ISSUE TITLE
Safari prices ribbon Title show bug

### ISSUE THREAD

**Issue by Caij** [onwidget/astrowind#474]
![image](https://github.com/onwidget/astrowind/assets/8597839/70c716f4-214d-49cc-8239-ec7c20d7e8bd)

**Comment by prototypa** [comment]
Hi @Caij 

What type of device are you testing on? What operating system and what version of Safari?

On several of the devices we have tested, including iPad, it works well.

<img width="1317" alt="Screenshot 2024-06-22 at 7 25 27 PM" src="https://github.com/onwidget/astrowind/assets/54446028/fb7407fb-aab5-4521-a796-e76a5e76bc3b">

**Comment by Caij** [comment]
![image](https://github.com/onwidget/astrowind/assets/8597839/249941de-d0cf-44c1-978e-9da4fb075209)

**Comment by Harold-Anderson** [comment]
Safari uses WebKit.  You will have to add css specific for these browsers.  For instance:

```
  details summary::-webkit-details-marker {
    display: none; /* Hide the default marker in WebKit browsers */
  }
```

You can see how to do this in my repo:  [https://github.com/Harold-Anderson/acfo](https://github.com/Harold-Anderson/acfo)

**Comment by Caij** [comment]
I upgraded my system version, and now everything is working fine. I can no longer reproduce this issue.
