### ISSUE TITLE
BlogHighlightedPosts does not work

### ISSUE THREAD

**Issue by Harold-Anderson** [onwidget/astrowind#481]
BlogHighlightedPosts works suboptimally and is not documented.  In order to get it to work, you have to create an array in your index.astro page called 

`const postIds[] = {['foo.md','bar.md']}`

Then `BlogHighlightedPosts` will display `foo.md `first, then `bar.md`.

Please note that this is not how the list of blog articles in the menu works in Astrowind.   The list of blog articles in the menu displays the articles in reverse chronological order.  This is sometimes not what is wanted.   In order to fix this,  I changed the load function to order by id, which Astrowind defines as the name of the blog markdown file.  You can see this on my Github repository [here](https://github.com/Harold-Anderson/acfo/tree/ea2ccc7b27c87bf47c94e0552465b13e7f02db85).  Please note that you then need to rename your blog files in the order you would like to present them to readers.

**Comment by prototypa** [comment]
Hi @Harold-Anderson 

The purpose of this widget `BlogHighlightedPosts ` is to display a list of specific posts by id.

If what you need is to list the latest posts, for this you have this other widget `BlogLatestPosts`:

https://github.com/onwidget/astrowind/blob/main/src/components/widgets/BlogLatestPosts.astro

Used here: https://github.com/onwidget/astrowind/blob/main/src/pages/homes/personal.astro#L396

**Comment by Harold-Anderson** [comment]
That is correct.  I am sorry if I was unclear.  BlogLatestPosts works correctly, but BlogHighlightedPosts is not documented.  My point in this issue is to point out how BlogHighlightedPosts works, since it is not documented, and provide a link to a working implementation. @prototypa
