### ISSUE TITLE
Images Distorted in Firefox on macOS and Windows After Scrolling

### ISSUE THREAD

**Issue by rekombination** [onwidget/astrowind#482]
I am experiencing an issue in Firefox where images are sometimes displayed distorted after scrolling. This problem occurs on both macOS and Windows platforms. The issue seems to be related to the CSS property content-visibility: auto;.

Steps to Reproduce:

1.     Open Firefox on either macOS or Windows.
2.     Visit a webpage with multiple images. (e.g. about us)
3.     Scroll down to the bottom of the page.
4.     Scroll back up so that the images re-enter the viewport.

Expected Behavior:

Images should display correctly and maintain their original aspect ratio and quality.

Actual Behavior:

Some images appear distorted, stretched, or compressed after they re-enter the viewport following a scroll action.
Workaround: When the following CSS option is commented out in the Layout.astro file, the issue does not occur:
```
img {
    content-visibility: auto;
}
```

Screenshots:

<img width="1567" alt="Bildschirmfoto 2024-07-10 um 12 19 46" src="https://github.com/onwidget/astrowind/assets/35768138/31597f8d-b4c8-4fb0-8b76-b4339c9e0071">
<img width="1567" alt="Bildschirmfoto 2024-07-10 um 12 22 29" src="https://github.com/onwidget/astrowind/assets/35768138/219b2b59-8223-4647-8bb4-1c90a57c9e5d">
<img width="1567" alt="Bildschirmfoto 2024-07-10 um 12 34 20" src="https://github.com/onwidget/astrowind/assets/35768138/db21e794-1f4a-416d-833b-a060c074f66d">
<img width="1567" alt="Bildschirmfoto 2024-07-10 um 12 34 27" src="https://github.com/onwidget/astrowind/assets/35768138/c94d7afc-d004-4ac4-b222-82c044a81a11">

Could you please investigate and provide a fix for this issue? 
It significantly affects the user experience, and any help would be greatly appreciated. Thank you!

**Comment by prototypa** [comment]
Hi @rekombination 

After trying many things, finally to solve it we have eliminated the style that you mentioned:

```
img {
    content-visibility: auto;
}
```

Fixed with: https://github.com/onwidget/astrowind/commit/ab746d051378b8b15dd83c544cf7b4be8aced27b

Thanks
