### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by Hemanshu2003** [onwidget/astrowind#483]
when i chick on the wifi button on the website it shows me this "This XML file does not appear to have any style information associated with it. The document tree is shown below. "
pls have a look
thank you

**Comment by prototypa** [comment]
Hi @Hemanshu2003 

Can you give me more information about what you mean by the Wifi Icon? 
Please send us a screenshot or the location of the file you mention.

We are closing this ticket until we have more information.
