### ISSUE TITLE
Icon replacement

### ISSUE THREAD

**Issue by Eventidus** [onwidget/astrowind#485]
![image](https://github.com/user-attachments/assets/717707e0-1888-4336-8b40-4bf53f4f53da)
Hello, I would like to ask how to change these icon symbols? I can't find the entry point for changing them.

**Comment by prototypa** [comment]
Hi @Eventidus 

If you go to the home page you will see that the names of the icons are passed by parameter:

https://github.com/onwidget/astrowind/blob/main/src/pages/index.astro#L69

Those icon names follow a pattern `<icon pack name>:<icon name>`, for example `tabler:brand-tailwind`

You can find more information about how to use the icon library and how to find the icons in these two links:

- https://www.astroicon.dev/
- https://iconify.design/
