### ISSUE TITLE
cart.json issue?

### ISSUE THREAD

**Issue by sunitgvaswani** [onwidget/astrowind#487]
Having a cart.json issue that shows up on every project. Any idea how to solve or get rid of it? 

11:54:29 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/cart.json`.

Possible dynamic routes being matched: src/pages/[...blog]/[category]/[...page].astro, src/pages/[...blog]/[tag]/[...page].astro, src/pages/[...blog]/[...page].astro, src/pages/[...blog]/index.astro.
11:54:29 [404] /cart.json 6ms

**Comment by prototypa** [comment]
Hello @sunitgvaswani.

To try to help you resolve this error, you have to give me more details about your repo because the **AstroWind** template, if you install it from scratch, does not have any url or `cart.json` file

I'm going to close this issue until I have more information.
Thank you
