### ISSUE TITLE
The CJK characters in the navigation bar cannot be displayed horizontally

### ISSUE THREAD

**Issue by gitiy1** [onwidget/astrowind#490]
It'seems like CJK characters in the top menu would not be displayed horizontally and there were no errors shown in console or terminal.
![屏幕截图_20240725_153959](https://github.com/user-attachments/assets/c5f747cd-3932-439b-acf1-73f9e8d064ac)
![image](https://github.com/user-attachments/assets/35c005d5-fe22-48b1-bd7f-86ab5fbbb57d)

**Comment by prototypa** [comment]
Hi @gitiy1 

We have solved the problem with https://github.com/onwidget/astrowind/commit/37916f72537fa23e74fcbb431c76399aa786a668

Please review and let us know.
Thank you.
