### ISSUE TITLE
Console warnings

### ISSUE THREAD

**Issue by marcitqualab** [onwidget/astrowind#505]
Hello I have just set up this template into a new repo and on the first "npm run dev" i got this warning.

```
03:57:10 [astrowind] Astrowind `./src/config.yaml` has been loaded.
03:57:10 [types] Generated 1ms

 astro  v4.14.6 ready in 827 ms

┃ Local    http://localhost:3000/
┃ Network  http://172.21.0.2:3000/

03:57:10 watching for file changes...
(node:7226) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7226) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
03:57:12 [astro-icon] Loaded icons from flat-color-icons, tabler
03:57:14 [200] / 29ms
```

The app looks like is working fine, however it will be good to know if I can fix these warning and or if they are important to be investigated forward or this is something temporal that will be resolved on future releases.

Many thanks,
Marc,

**Comment by prototypa** [comment]
Hi @marcitqualab 

I don't get any warning here.. What version of node are you using?

**Comment by marcitqualab** [comment]
Hello André,

You can try on my taa-web repo <https://github.com/marcitqualab/taa-web>.
It contains the template and a minimal dev container with docker setup for
a local development environment.

You can open it with vscode and with the official dev containers extension
by microsoft you can build the local dev env. Once the dev env is up I just
run "pnpm run dev" or "npm run dev". After opening the app in the browser I
get the warnings.

[image: image.png]

Let me know if you have any questions.
Many thanks,



Merci, Thanks, Gracias :-)
---------------------------------------------------
Marc Andreu from IT Quality Lab Ltd.

**Comment by marcitqualab** [comment]
Hello André,

Where you able to reproduce warnings issue?

Thanks,
Marc,

Merci, Thanks, Gracias :-)
---------------------------------------------------
Marc Andreu from IT Quality Lab Ltd.

**Comment by Lezitoune** [comment]
Hi @marcitqualab @prototypa 

Had the latest node v22.8.0 installed and got the same warning message.
Uninstalled node and reinstalled node LTS v20.17.0 and no more warnings.

Hope this helps

Oh and by the way tks for all the great work

**Comment by marcitqualab** [comment]
Awesome, thanks for the info!

Merci, Thanks, Gracias :-)
---------------------------------------------------
Marc Andreu from IT Quality Lab Ltd.

**Comment by prototypa** [comment]
Hi @Lezitoune and @marcitqualab 

Fixed with https://github.com/onwidget/astrowind/commit/b8ac443d44b571641557c9ce114cc823e98faf41

Thanks!
