### ISSUE TITLE
Problem deploying to netlify

### ISSUE THREAD

**Issue by miklereverie** [onwidget/astrowind#509]
When deploying the project to netlify, for some reason the images don't show up correctly, it's like it can't find them:
![image](https://github.com/user-attachments/assets/32159420-5c9c-4023-b971-5f07be914591)

It works fine  locally running pnpm run dev, problem is when I deploy it to netlify.

I'm well aware this is not necessarily a problem with the theme, just asking in case anyone knows how to fix it or stumbled across this issue in the past because I'm losing my mind.

Thanks in advance for your time.

EDIT:  The problem also happens when  running pnpm run preview, so I'm guessing it has something to do with astro not "shipping" the images correctly to the dist folder when I run build? Any other clues will we welcome!

**Comment by jjjhill** [comment]
How are you referencing your image sources in your code? I had a similar problem and fixed it by referencing the images like this:
<Image src="src/assets/images/X.svg" />

**Comment by jjjhill** [comment]
In fact in most cases, i had to import them via relative path:
`import dataIcon from '../../assets/images/data.svg'`
`<Image src={dataIcon} />`

**Comment by miklereverie** [comment]
> In fact in most cases, i had to import them via relative path: `import dataIcon from '../../assets/images/data.svg'` `<Image src={dataIcon} />`

Thank you so much, using relative paths fixed it! 
I'm still getting another problem where the styles for the dark and light theme don't switch properly when clicking the switcher both in netlify and pnpm run preview. Not getting any errors in the console, just these warnings:
![image](https://github.com/user-attachments/assets/2fbaf5f7-0d92-45c7-80db-0bd40f6e1d53)


As usual, any ideas would be greatly appreciated!

**Comment by prototypa** [comment]
Hi @jjjhill and @miklereverie 

Try using `"~/assets/images/data.svg"`

It is the way defined in **AstroWind** to import images into the `src/assets/` folder
