### ISSUE TITLE
Rules missing in generated dist/robots.txt

### ISSUE THREAD

**Issue by lionelduriez** [onwidget/astrowind#524]
After building astrowind with latest main version available on 2024-10-03, dist/robots.txt file only contains the following Sitemap entry:

`Sitemap: https://astrowind.vercel.app/sitemap-index.xml`

Rule defined in public/robots.txt is missing.

The behavior has been different in the past: content of public/robots.txt was merged with sitemap entry.
I think this is the result of an evolution in Astro Sitemap code. As the offical [Astro Sitemap documentation](https://docs.astro.build/en/guides/integrations-guide/sitemap/) does not mention that content of public/robots.txt is merged with Sitemap entry I think it is not a bug within Astro Sitemap.

As a quick fix on my project, I have added the Sitemap entry to public/robots.txt file and the end result is fine: my public/robots.txt is entirely present in the generated file dist/robots.txt.

For Astrowind, maybe the dynamic generation of robots.txt using src/pages/robots.txt.ts as explained in the official documentation would be the way to go.

**Comment by prototypa** [comment]
Hi @lionelduriez 

Thanks for letting us know. **AstroWind** code was prepared to automatically add the Sitemap to `public/robots.txt`. 

https://github.com/onwidget/astrowind/blob/main/vendor/integration/index.ts#L75

Something has changed in the latest versions of _Astro_ that is not letting this happen. We will review and let you know.

**Comment by prototypa** [comment]
Hi @lionelduriez 

We fix the problem with :https://github.com/onwidget/astrowind/commit/d942f2b9f6d4a9c475d1f66cee988b5caa3de77b

Currently I still don't know why that stopped working, if it was something related to the version of Node and the function we were using. It definitely had nothing to do with _Astro_.

It's already working.

We are evaluating whether for the **AstroWind v2** version we move that entire process to what the sitemap documentation specifies using a `robots.txt.ts`.

Thank you
