### ISSUE TITLE
Astrowind Image Optimization for remote Images does not work. 

### ISSUE THREAD

**Issue by randomsnowflake** [onwidget/astrowind#530]
I'm serving images from a local CMS server. I display those images using the `<Image>` or `<img>` components inside astrojs.

I expect it to download the remote images and serve them from astrojs. However, it just outputs the original image file, exposing my CMS.

Sample code: 

```javascript

// Usage
import Image from '~/components/common/Image.astro';
 <Image
    src="http://localhost:8055/assets/bcc93e95-e42c-4382-aec5-6fd2809c2c7d"
    alt="test"
    width={400}
    height={100}
    loading="lazy"
    decoding="async"
  />

// Config
export default defineConfig({
  image: {
    domains: ["localhost:8055", "localhost"],
	},  
...

```

If I change the Image import to `import { Image } from 'astro:assets';` it works. But then I'm not using the astrowind components.

Thanks for pointing me in the right direction.

**Comment by prototypa** [comment]
Hi @randomsnowflake 

We have solved it with https://github.com/onwidget/astrowind/commit/21830b3d58b06f8f13b9c946facdad531c6e061e. 

Try now and let us know.
Thank you.
