### ISSUE TITLE
Inquiry: Support for Astro 5 in Astrowind Theme

### ISSUE THREAD

**Issue by divya-binil** [onwidget/astrowind#564]
Hi,

First, I’d like to thank you for the amazing work you’ve done with the Astrowind theme.

I noticed that Astro 5 was recently released, bringing some significant updates to the framework. I was wondering if the Astrowind theme is currently compatible with Astro 5 or if there are plans to update it to support the latest version.

Your clarification will help me plan my project accordingly. Thank you in advance for your time and effort!

**Comment by ttys3** [comment]
+1 https://astro.build/blog/astro-5/

**Comment by prototypa** [comment]
Hi @divya-binil and @ttys3 

The latest version available in the repo is now using Astro v5.

**Comment by divya-binil** [comment]
Thank you for confirming that the latest version of the Astrowind theme supports Astro 5.

I’m currently using an older version of Astrowind in a few applications, and we’ve added some additional components to suit our requirements. Incorporating the updates manually seems challenging due to the potential differences.

Could you please guide me on the best way to upgrade to the latest Astro 5-compatible version? Specifically:

- Are there any recommended steps to merge the new version while retaining existing additions?
- Do you suggest a particular approach (e.g., starting fresh and migrating, or directly updating)?
- Are there any critical files or configurations I should focus on during the update?

I appreciate your support and guidance!
