### ISSUE TITLE
script tag is giving could not import error

### ISSUE THREAD

**Issue by koolkunz** [onwidget/astrowind#67]
Just adding a simple script tag which logs Hello to a page gives this error:

```
 error   Could not import `/src/pages/contact-us.astro?astro&type=script&index=0&lang.ts`.
  Hint:
    This is often caused by a typo in the import path. Please make sure the file exists.
  Stacktrace:
Error: failed to load module for ssr: /src/pages/contact-us.astro?astro&type=script&index=0&lang.ts
    at instantiateModule (file:///D:/DCS%20Projects/Local/astrowind/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53281:15)
```
This is the .astro file for the page:
```
---
import { SITE } from '~/config.mjs';
import { getCanonical, getHomePermalink } from '~/utils/permalinks';
import Layout from '~/layouts/PageLayout.astro';
import Breadcrumbs from '~/components/widgets/Breadcrumbs.astro';
import Title from '~/components/widgets/Title.astro';

const {title = 'Contact Us'} = Astro.props;

const meta = {
	title: title + ' - ' + SITE.title,
	description: SITE.description,
	canonical: getCanonical(getHomePermalink()),
};
---
<Layout {meta}>
	<Breadcrumbs />
	<Title title={title}/>
	<p class="font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">We’re here to help! Tell us what you’re looking for and we’ll get back to you as soon as possible.</p>
</Layout>
<script>
	console.log("Test");
</script>
```

If I remove the script tag at the end the same page loads fine without any errors

**Comment by koolkunz** [comment]
Hi, thanks for the reply, it seems it is working for me if I build the project first and then run the preview using npm run build and npm run preview. But if I run the dev server directly using npm run dev it gives me the error.

**Comment by koolkunz** [comment]
And I just tried cloning astrowind as a fresh project, and just added 
```
<script>
	console.log("Test");
</script>
```

to the end of the index.astro file and the error is still comming in npm run dev:
```
D:\test astrowind\astrowind>npm run dev

> @onwidget/astrowind@0.8.5 dev
> astro dev

[MDX] Now inheriting remark and rehype plugins from "markdown" config.
If you applied a plugin to both your Markdown and MDX configs, we suggest removing the duplicate MDX entry.
See "extendPlugins" option to configure this behavior.
   astro  v1.6.15 started in 745ms

  ┃ Local    http://127.0.0.1:3000/
  ┃ Network  use --host to expose

11:24:38 am [astro] reload D:/test astrowind/astrowind/src/pages/index.astro
 error   Could not import `/src/pages/index.astro?astro&type=script&index=0&lang.ts`.
  Hint:
    This is often caused by a typo in the import path. Please make sure the file exists.
  Stacktrace:
Error: failed to load module for ssr: /src/pages/index.astro?astro&type=script&index=0&lang.ts
    at instantiateModule (file:///D:/test%20astrowind/astrowind/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53281:15)
```

**Comment by koolkunz** [comment]
My node version is v16.17.1

**Comment by delphinas** [comment]
I have exactly the same error when importing astro-embed plugin. Mac OS, node is 14

**Comment by koolkunz** [comment]
Hi @prototypa did you find anything related to node? any other node version you can recommend that I should try?

**Comment by koolkunz** [comment]
@prototypa I have also tried using a different theme like https://github.com/mhyfritz/astro-landing-page and using script tag works fine with it on my system. So its not a problem with astro in general with my environment.

**Comment by koolkunz** [comment]
@prototypa You are on the right track, Astro Ink template also gives me a similar problem, the script tag on the BaseHead.astro file https://github.com/one-aalam/astro-ink/blob/main/src/components/BaseHead.astro gives the same error
```
error   Could not import `/src/components/BaseHead.astro?astro&type=script&index=0&lang.ts`.
  Hint:
    This is often caused by a typo in the import path. Please make sure the file exists.
  Stacktrace:
Error: failed to load module for ssr: /src/components/BaseHead.astro?astro&type=script&index=0&lang.ts
    at instantiateModule (file:///D:/Downloads/test%20astro/astro-ink/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53281:15)
```
If I remove the script tag it runs fine, and then if I add a script tag to index.astro the error is back.

**Comment by koolkunz** [comment]
@prototypa I found the solution on astro official discord, it seems it's an issue caused by vite if we have any spaces in the project repo path, so simply changing my path from 'D:/DCS Projects/Local/astrowind' to 'D:/DCS-Projects/Local/astrowind' fixed the issue (replaced ' ' with '-').

Such a silly issue. Thanks for all your help and support. I am closing the issue.
